### ISSUE TITLE
Mews API changes: spaces -> resources

### ISSUE THREAD

**Issue by stang704** [dneise/MeHR#16]
Hi Dominik, hope you're well. I'm reaching out here about the API changes that will be deployed tomorrow around noon CET. 

We did multiple email outreaches but I suspect we didn't manage to reach you, the author, because the email addresses listed for each MeHR integration in our system was the hotel's email address and we hadn't thought of that when putting together the mailing list.

Essentially the change is about renaming "Spaces" to "Resources" in the API request. The Spaces properties in valid endpoints will be ignored (e.g. reservations/getAll), whereas some endpoints will be completely replaced (e.g. spaces/getAll --> replaced by resources/getAll).

Some particular elements to note: 
1. "ServiceIds" will be a required field in `reservations/getAll`. It's the `Reservable` type [service](1) that will be accepted. Most hotels will have only one. Some might have two in the future, if they offer other kinds of reservations through Mews (e.g. booking a conference room, day use, etc). These are why there can be multiple Reservable services. Properties can also manually find it in the URL. (instructions: https://help.mews.com/en/articles/4452109-how-to-find-product-id-service-id-accounting-category-id-in-mews) 

2. The extents in the request are also now more granular:
```
"Resources": true,
"ResourceCategories": false
"ResourceCategoryAssignments": false,
```

Full list of changes can be found here: https://mews-systems.gitbook.io/connector-api/changelog#2nd-july-2020-11-30-utc

Is there any way you could update the MeHR service to work with the API changes? 
If the service updates can be pushed to each property automatically, that would be great. Otherwise, please let me know and we can reach out to the properties individually and ask them to manually update it, if needed. 

If any issues, please don't hesitate to let me know!
Sylvia

[1]: https://mews-systems.gitbook.io/connector-api/operations/services#service-type

**Comment by dneise** [comment]
Hello Sylvia, thanks for opening this issue and letting me know. Currently I am super busy, so I will not be able to produce an update until the deadline. 
This means the hotels in question will for some days not send reports to the Zurich cantonal police... but since we are in a pandemic and not many people stay in hotels ... I guess that is acceptable.

Unfortunately I cannot push updates automatically to the customer. This project is really just a simple executable, running on the customers site. So they will have to download and "install" the executable themselves (or the IT guys have to do it).
So it would be great, if I could just create the update (test it with the welcome hotels, which are basically family, so I am working closely with them) and then let you know to inform any other users of MeHR.

Does that sound ok for you?

I'd say I can look into this at the weekend. So by next monday, I might have an update... let's hope.

**Comment by stang704** [comment]
Hi Dominik, 

I think that would be okay. I'll let our Customer Support team know to give the hotels a heads up to maybe handle it manually just in case they do have some guests. 

Your plan sounds good - to update & test. Once done, I can coordinate with the team at Mews to communicate the change to the other Mews hotels that are using the integration. 

Thank you so much for your time!

**Comment by dneise** [comment]
Hello Sylvia .. short update.
I finally started working on it .. I think I got it working on python .. now I need to build the windows executable and deliver it to the welcome hotels to try it out (this will happen this evening)
 ... and then I will upload a new release here on github and you can inform the other customers. 
Cheers

**Comment by stang704** [comment]
Hi Dominik, sorry for the delayed reply. 

I was playing with some auto-filing rules in my inbox and it muted all Github notification emails. 

Thank you so much for the update! How did the testing go with Welcome hotels?

**Comment by dneise** [comment]
Hi Sylvia,

the version is out. The "How to update video" (in german) is out as well.
Can all be found here:
https://github.com/dneise/MeHR/releases

**Comment by dneise** [comment]
Sorry for taking so long .. video production is not the easiest for me right now.
